/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author facun
 */
public class PrimerPantalla extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrimerPantalla.class.getName());

    /**
     * Creates new form PrimerPantalla
     */
    public PrimerPantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_ver_animales = new javax.swing.JButton();
        btn_agregar_animales = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_ver_animales.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_ver_animales.setText("Ver animales");
        btn_ver_animales.setFocusable(false);
        btn_ver_animales.addActionListener(this::btn_ver_animalesActionPerformed);

        btn_agregar_animales.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_agregar_animales.setText("Agregar animales");
        btn_agregar_animales.setFocusable(false);
        btn_agregar_animales.addActionListener(this::btn_agregar_animalesActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_ver_animales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_agregar_animales, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(btn_agregar_animales, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btn_ver_animales, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregar_animalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_animalesActionPerformed
        this.dispose();
        AgregarAnimalPantalla pp = new AgregarAnimalPantalla();
        pp.setVisible(rootPaneCheckingEnabled);
        pp.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btn_agregar_animalesActionPerformed

    private void btn_ver_animalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ver_animalesActionPerformed
        this.dispose();
        VerAnimalesPantalla pp = new VerAnimalesPantalla();
        pp.setVisible(rootPaneCheckingEnabled);
        pp.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_ver_animalesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar_animales;
    private javax.swing.JButton btn_ver_animales;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
